raise AttributeError('fail on purpose')